version: '3.9'
services:
  evolution-api:
    build: .
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
      - DATABASE_CONNECTION_URI=${DATABASE_CONNECTION_URI}
      - REDIS_CONNECTION_URI=${REDIS_CONNECTION_URI}
