version: '3.9'
services:
  evolution-api:
    build: .
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Variáveis de ambiente da API Evolution
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://${PGUSER}:${PGPASSWORD}@postgres:5432/${PGDATABASE}
      - DATABASE_ENABLED=true
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DATABASE_SAVE_DATA_LABELS=true
      - DATABASE_SAVE_DATA_HISTORIC=true
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: evolution_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      # Configuração inicial do banco de dados
      POSTGRES_USER=evolution_user
      POSTGRES_PASSWORD=evolution_password
      POSTGRES_DB=evolution_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
